restrict mouse events that trigger click
open-cogsci/OpenSesame pull request #798
Opened 2023-09-15 09:14 UTC by eort

All mouse events (left/right/middle click, as well as turning the wheel and what not is currently triggering mouse events. 
This PR limits it to left/right/middle clicks by hard coding it. 

I couldn't see a benefit of making it a parameter. But maybe, we could restrict it even more? Like only left-clicks?

2023-10-03 14:12 UTC, smathot requested changes
The correct keyword is `buttonlist`, not `button_list`! The problem with this is not so much the fix, which is easy, but the fact that you submitted the PR without testing it. Could you update the PR, and in the future *always* test a PR before opening it.

2023-10-03 14:55 UTC, eort commented
Sure, sorry. Will do!

2023-10-03 14:57 UTC, eort commented
Do you have actually some automated test battery of sorts? In this particular case with the mouse buttons, testing it is rather easy, but for bigger changes it becomes quite hard to oversee effects of new code, especially considering different setups, etc.

2023-10-04 06:20 UTC, smathot commented
Thanks for the update!

> Do you have actually some automated test battery of sorts? In this particular case with the mouse buttons, testing it is rather easy, but for bigger changes I imagine it to be quite tricky to oversee all the effects of new code, especially considering different setups, etc.

Partly. There are test cases (unittests) included with the source code which you can run with `pytest`. However, these only test those aspects of the code that don't require user interaction, such as parsing of OpenSesame script. Of course a lot of the functionality is about user interaction so the unittests are far from comprehensive.

It is possible to write unittests for interactions too. But that's tricky and I never got around to doing that.

2023-10-04 09:59 UTC, merged